/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chess212;

public class Main {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(final String[] args) {
    System.out.println(new Main().getGreeting());
  }
}
