name: Release Jar

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release_type:
        description: "major|minor|patch|release|prerel"
        default: "patch"
        required: true
      release_version:
        description: "Optional release version, e.g. 0.2.0"
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
     
      - name: "Create next release tag"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEMVER_BUMP: ${{ github.event.inputs.release_type }}
        run: |
          if [[ -n "${{ github.event.inputs.release_version }}" ]]
          then
            next_release_version="v${{ github.event.inputs.release_version }}"
          else
            previous_release_version="$(gh api /repos/:owner/:repo/releases --jq '.[0].tag_name')"
            echo "PREVIOUS RELEASE VERSION: $previous_release_version"
            wget https://raw.githubusercontent.com/fsaintjacques/semver-tool/3.3.0/src/semver
            # https://github.com/fsaintjacques/semver-tool
            next_release_version="v$(./semver bump ${SEMVER_BUMP:=patch}  $previous_release_version)"
          fi
          echo "NEXT RELEASE VERSION: $next_release_version"
          gh api -X POST /repos/:owner/:repo/git/refs \
            --field ref="refs/tags/$next_release_version" \
            --field sha="$GITHUB_SHA"

      - name: "Fetch new tag"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run CI with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: ci

      - name: Build Jars 
        id: build
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: clean jar fatJar
      
      - name: Publish release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            app/build/libs/*.jar


